#!/bin/bash

src=/etc/nginx/

/usr/bin/inotifywait -rmq  -e modify,delete $src |  while read  event
do
        Yes=`/usr/sbin/nginx -t 2>temp.txt ; grep successful temp.txt  | wc -l ; rm -rf  temp.txt`
# old : Yes=`/usr/local/nginx/sbin/nginx -t 1>/dev/null 2>temp.txt ; grep successful temp.txt  | wc -l ; rm -rf  temp.txt`
        if [ $Yes -eq 1 ];then
                kill -HUP `cat /var/run/nginx.pid`
        else
                echo `hostname`":nginx.conf configure error."
        fi
done
