#!/bin/bash

#description: opencdn
#chkconfig: 2345 20 81

EXEC_PATH=/usr/local/nginx/sbin
EXEC="opencdn"
EXEC_CACHE="search_url"
EXEC_INFO="send_info"
PID_FILE="/var/run/$EXEC.pid"
OPENCDN_LOG_PATH="/var/log/opencdn"

. /etc/rc.d/init.d/functions

[ -x $EXEC_PATH/$EXEC_INFO ] || echo "ERROR: $EXEC_INFO not found"
[ -x $EXEC_PATH/$EXEC_CACHE ] || echo "ERROR: $EXEC_CACHE not found"
[ -f "$PID_FILE" ] || touch $PID_FILE

function change_console_ip()
{
	new_console_ip=`cat /etc/opencdn/opencdn.conf | grep "Console_IP" | awk -F = '{print $2}'`
	[ ! -z "${new_console_ip}" ] || return 1

	#change console IP of rsync
	rsync_old_ip=`cat /etc/rsyncd.conf | grep "hosts allow" | awk -F = '{print $2}'`
	if [ "${rsync_old_ip}" != " $new_console_ip" ]
	then
		sed "s/$rsync_old_ip/ $new_console_ip/g" -i /etc/rsyncd.conf
	fi

	#change console IP of syslog
	syslog_old_ip=`cat /etc/syslog-ng/syslog-ng.conf | grep "udp(" | head -1 | awk -F \" '{print $2}'`
	if [ "${syslog_old_ip}" != "$new_console_ip" ]
	then
		sed "s/$syslog_old_ip/$new_console_ip/g" -i /etc/syslog-ng/syslog-ng.conf
	fi
}

stop()
{
		echo "Stoping $EXEC ..."
		ps aux | grep "$EXEC_INFO" | kill -9 `awk '{print $2}'` >/dev/null 2>&1
		ps aux | grep "$EXEC_CACHE" | kill -9 `awk '{print $2}'` >/dev/null 2>&1

		kill -9 `ps aux | grep 'rsync' | awk '{print $2}'` > /dev/null 2>&1
		service syslog-ng stop
		echo "" > $PID_FILE
		usleep 100
		echo "Shutting down $EXEC: [  OK  ]"    
}

start()
{
		if [ "`cat $PID_FILE`" == "running" ];then
			echo "$EXEC is running"
			exit 1
		fi
		change_console_ip
		echo "Starting $EXEC ..."
		rm -f /var/run/rsyncd.pid
		/usr/bin/rsync --daemon 
		service syslog-ng start

		nohup /bin/bash /usr/local/nginx/sbin/search_url >> ${OPENCDN_LOG_PATH}/search_url.log 2>&1 &
		nohup /bin/bash /usr/local/nginx/sbin/send_info >> ${OPENCDN_LOG_PATH}/send_info.log 2>&1 &
		echo "running" > $PID_FILE
		usleep 100
		echo "Starting $EXEC: [  OK  ]"        
}

restart()
{
	stop
	start
}

status()
{
       if [ "`cat $PID_FILE`" == "running" ]
       then
              echo "$EXEC is running"
       else
              echo "$EXEC is not running"
       fi       
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
    status)
        status
        ;;
	*)
		echo "Usage: service $EXEC {start|stop|restart|status}"
		exit 1
esac

exit $?
